#!/bin/bash

#SBATCH --partition=debug
#SBATCH --time=01:00:00
#SBATCH --job-name=genpsf
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1

# load CHARMM environment variables
module load intel/2021.1.2
module load charmm/c45b2_openmm_intel

# load perturbation variables based on nsubs
nsubs=(`cat nsubs`)   # a space delimited list of subs at each site
nsites=${#nsubs[@]}
allsubs=''
nblocks=0
for ((a=1;a<=${#nsubs[@]};a+=1)); do
    allsubs+="nsubs${a}=${nsubs[(($a-1))]} "
    nblocks=$(($nblocks + ${nsubs[(($a-1))]}))
done

# Run the simulation
export OMP_NUM_THREADS=1
mpirun -np 1 $CHARMMEXEC nsites=$nsites nblocks=$nblocks $allsubs -i genpsf.inp -o genpsf.out

# Finished
echo "FINISHED"

exit

