#!/bin/bash

#SBATCH --partition=debug
#SBATCH --time=01:00:00
#SBATCH --job-name=gen_omm
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1

# Load OpenMM environment
source activate omm102py39

# Setup necessary files & directories
#cp ../1.gen_charmm_psf/patch.* ./
#ln -s ../1.gen_charmm_psf/prep/ ./

# Run the simulation
time python setupOMMSystem.py

# Finished 
echo "FINISHED"

exit
