#!/bin/bash

#SBATCH --partition=debug
#SBATCH --time=0-1:00:00
#SBATCH --job-name=gen_omm_cmet-1
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
######SBATCH --gres=gpu:1

# Load OpenMM environment
conda activate omm100-rdkit

# Setup necessary files & directories
cp ../2.gen_charmm_psf/patch.* ./
ln -s ../2.gen_charmm_psf/prep/ ./

# Run the simulation
time python setupSystem_NBFIXs.py

# Finished 
echo "FINISHED"

exit
