#!/bin/bash

#SBATCH --partition=debug
#SBATCH --time=0-1:00:00
#SBATCH --job-name=gen_omm_cmet-1
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
######SBATCH --gres=gpu:1

# You have to specify which gpu you want your job to run with
#####SBATCH --gres=gpu:p100:1  (runs 50 mins per ns)
#####SBATCH --gres=gpu:v100:1  (runs 25 mins per ns)

#module unload python
#module load anaconda cudatoolkit/10.0
conda activate omm100-rdkit

# Setup necessary directories
#cp ../gen_charmm_psf/patch.* ./
#ln -s ../../solv_prep/ ./

# Run the simulation
time python setupSystem_NBFIXs.py


# Finished 
echo "FINISHED"

exit
